project_id = "tcdlhmojircjhwqmvila"

[functions.fetch-survivor-news]
verify_jwt = false

[functions.jeffbot]
verify_jwt = false

[functions.fetch-cast-images]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false

[functions.suggest-bug-response]
verify_jwt = false